@startuml
!pragma layout smetana
skinparam shadowing false
skinparam actorBorderColor #1B365D
skinparam actorFontColor #1E232D
skinparam usecaseBackgroundColor #FFFFFF
skinparam usecaseBorderColor #1B365D
skinparam usecaseFontColor #1E232D
skinparam rectangleBorderColor #1B365D
skinparam rectangleBackgroundColor #F8FAFC
skinparam arrowColor #1B365D

actor "Researcher" as Researcher

rectangle "Research Platform" {
  usecase "Submit Research" as Submit_Research
  usecase "Manage Submissions" as Manage_Submissions
  usecase "Track Submission and Presentation Status" as Track_Submission_and_Presentation_Status
}

actor "Reviewer/Admin" as Reviewer_Admin

Researcher -- Submit_Research
Reviewer_Admin -- Manage_Submissions
Researcher -- Track_Submission_and_Presentation_Status

@enduml
